channel_sources:
  - zeroae,conda-forge,defaults
channel_targets:
  - zeroae main
dlib_variant_version:
  - 1.1.0
  - 1.2.0
dlib_variant_str:
  - cpu
  - cuda
zip_keys:
  - - dlib_variant_version
    - dlib_variant_str
