package:
  name: _dlib_mutex
  version: {{ dlib_variant_version }}

build:
  # The build number must always be set to 0.
  # Use conda_build_config.yaml to make a new release.
  noarch: generic
  number: 0
  string: {{ dlib_variant_str }}

test:
  commands:
    - /bin/true

about:
  home: https://github.com/zeroae/_dlib_mutex-feedstock
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: "The dlib mutex package."
  description: |
    We support different variants of darknet:
    `cpu`(default), which is compiled with CPU only sppport
    `cuda`, which is compiled with CUDA and CPU suppor
extra:
  recipe-maintainers:
    - sodre
